# /// script
# requires-python = ">=3.10"
# dependencies = ["jsonschema==4.26.0"]
# ///
"""Validate every AS>TUI frame against schemas generated by the installed CLI.

Run with uv run codex-wire-schema.py SCHEMA_DIR WIRE_NDJSON.
Unknown methods, unmatched responses and malformed lines fail closed.
"""
import json
from pathlib import Path
import re
import sys

from jsonschema import Draft7Validator

RESPONSE_NAMES = {
    "account/read": "GetAccountResponse",
    "account/rateLimits/read": "GetAccountRateLimitsResponse",
    "thread/name/set": "ThreadSetNameResponse",
}


def validate_wire(schema_root, frames):
    validators = {}
    requests = {}
    counts = {}
    failures = []

    def check(name, payload):
        if name not in validators:
            paths = [schema_root / version / (name + ".json") for version in ["v2", "v1", ""]]
            path = next((p for p in paths if p.is_file()), None)
            if path is None:
                raise ValueError("unmapped schema: " + name)
            schema = json.loads(path.read_text())
            Draft7Validator.check_schema(schema)
            validators[name] = Draft7Validator(schema)
        errors = list(validators[name].iter_errors(payload))
        if errors:
            raise ValueError("; ".join(f"{list(e.absolute_path)}: {e.message[:500]}" for e in errors[:3]))

    for line, frame in enumerate(frames, 1):
        key = (frame.get("connection"), frame.get("id"))
        if frame.get("direction") == "TUI>AS" and "method" in frame and "id" in frame:
            requests[key] = frame["method"]
        if frame.get("direction") != "AS>TUI":
            continue
        kind = "unknown"
        try:
            payload = {k: v for k, v in frame.items() if k not in {"direction", "connection", "at"}}
            if "method" in frame:
                kind = "serverRequest" if "id" in frame else "notification"
                check("ServerRequest" if "id" in frame else "ServerNotification", payload)
            elif "result" in frame or "error" in frame:
                kind = "response"
                method = requests.pop(key, None)
                if method is None:
                    raise ValueError("response without matching client request")
                if "error" in frame:
                    check("JSONRPCError", payload)
                else:
                    check("JSONRPCResponse", payload)
                    name = "".join(p[0].upper() + p[1:] for p in re.split(r"[/_]", method))
                    check(RESPONSE_NAMES.get(method, name + "Response"), frame["result"])
            else:
                raise ValueError("unrecognized outbound frame")
        except Exception as error:
            failures.append({"line": line, "kind": kind, "message": str(error)})
        counts[kind] = counts.get(kind, 0) + 1
    return {"checked": sum(counts.values()), "by_kind": counts, "failures": failures,
            "clean": bool(counts) and not failures}


if __name__ == "__main__":
    try:
        frames = [json.loads(line) for line in Path(sys.argv[2]).read_text().splitlines()]
        report = validate_wire(Path(sys.argv[1]), frames)
    except Exception as error:
        report = {"clean": False, "failures": [{"message": str(error)}]}
    print(json.dumps(report, indent=2))
    sys.exit(0 if report["clean"] else 1)
